"""Add family fields to student

Revision ID: 864959fe162d
Revises: a295114ce736
Create Date: 2026-10-04 14:40:13.099977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864959fe162d'
down_revision: Union[str, Sequence[str], None] = 'a295114ce736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('father_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('mother_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('caste', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'caste')
    op.drop_column('students', 'mother_name')
    op.drop_column('students', 'father_name')
    # ### end Alembic commands ###
