"""add activated_at, failed_attempts, roll_no, guardian_phone, debarred_reason, current_percentage, audit actions

Revision ID: a295114ce736
Revises: 365e69631458
Create Date: 2026-10-03 14:32:17.369948

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a295114ce736"
down_revision: str | Sequence[str] | None = "365e69631458"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "password_reset_tokens",
        sa.Column(
            "failed_attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
    )
    # Add roll_no as nullable first, then populate, then make not null
    op.add_column("students", sa.Column("roll_no", sa.String(length=30), nullable=True))
    op.execute("UPDATE students SET roll_no = 'TEMP_' || id WHERE roll_no IS NULL")
    op.alter_column("students", "roll_no", nullable=False)
    op.add_column(
        "students", sa.Column("current_percentage", sa.Numeric(precision=5, scale=2), nullable=True)
    )
    op.add_column("students", sa.Column("guardian_phone", sa.String(length=20), nullable=True))
    op.add_column("students", sa.Column("debarred_reason", sa.Text(), nullable=True))
    op.create_index(op.f("ix_students_roll_no"), "students", ["roll_no"], unique=True)
    op.drop_column("students", "cgpa")
    op.add_column("users", sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True))
    # Update audit_logs action constraint to include new actions
    op.execute("ALTER TABLE audit_logs DROP CONSTRAINT ck_audit_logs_action")
    op.create_check_constraint(
        "ck_audit_logs_action",
        "audit_logs",
        "action IN ('create', 'update', 'delete', 'status_change', 'override', 'login', 'invite_sent', 'activation', 'login_failed', 'logout', 'import')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "activated_at")
    op.add_column(
        "students",
        sa.Column("cgpa", sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_students_roll_no"), table_name="students")
    op.drop_column("students", "debarred_reason")
    op.drop_column("students", "guardian_phone")
    op.drop_column("students", "current_percentage")
    op.drop_column("students", "roll_no")
    op.drop_column("password_reset_tokens", "failed_attempts")
    # Revert audit_logs action constraint
    op.execute("ALTER TABLE audit_logs DROP CONSTRAINT ck_audit_logs_action")
    op.create_check_constraint(
        "ck_audit_logs_action",
        "audit_logs",
        "action IN ('create', 'update', 'delete', 'status_change', 'override', 'login')",
    )
    # ### end Alembic commands ###
