"""add_created_at_to_import_job_errors

Revision ID: ccd726f95b7c
Revises: 864959fe162d
Create Date: 2026-10-04 19:37:40.230131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd726f95b7c'
down_revision: Union[str, Sequence[str], None] = '864959fe162d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_job_errors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_job_errors', 'created_at')
    # ### end Alembic commands ###
