"""add is_debarred to students

Revision ID: d640a391e285
Revises: 1ec092a37dbf
Create Date: 2026-10-03 11:47:16.465444

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d640a391e285"
down_revision: str | Sequence[str] | None = "1ec092a37dbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students",
        sa.Column("is_debarred", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "is_debarred")
    # ### end Alembic commands ###
